/*
 New BSD License <http://creativecommons.org/licenses/BSD/>
 Public Domain
 @author Benjamin Arthur Lupton <contact@balupton.com>
 @author James Padolsey <https://gist.github.com/527683>
 Public Domain
 @author Benjamin Arthur Lupton <contact@balupton.com>
*/
(function(h,k){h.History=h.History||{};h._History=h._History||{};var j=h.console||k,g=h.document,d=h._History,b=h.History,l=h.history;if(typeof b.initHtml5!=="undefined")throw Error("History.js HTML5 Support has already been loaded...");b.initHtml5=function(){if(typeof b.Adapter==="undefined")return false;b.options={hashChangeCheckerDelay:100,busyDelay:250};b.debug=function(){b.debug.enable&&b.log.apply(b,arguments)};b.debug.enable=false;b.log=function(){var a=typeof j!=="undefined",c=g.getElementById("log"),
e="\n"+arguments[0]+"\n",f;if(a){f=Array.prototype.slice.call(arguments);e=f.shift();typeof j.debug!=="undefined"?j.debug.apply(j,[e,f]):j.log.apply(j,[e,f])}f=1;for(n=arguments.length;f<n;++f){var i=arguments[f];if(typeof i==="object"&&typeof JSON!=="undefined")try{i=JSON.stringify(i)}catch(m){}e+="\n"+i+"\n"}if(c){c.value+=e+"\n-----\n";c.scrollTop=c.scrollHeight-c.clientHeight}else a||alert(e);return true};d.getInternetExplorerMajorVersion=function(){return d.getInternetExplorerMajorVersion.cached=
typeof d.getInternetExplorerMajorVersion.cached!=="undefined"?d.getInternetExplorerMajorVersion.cached:function(){for(var a=3,c=g.createElement("div"),e=c.getElementsByTagName("i");c.innerHTML="<\!--[if gt IE "+ ++a+"]><i></i><![endif]--\>",e[0];);return a>4?a:void 0}()};d.isInternetExplorer=function(){return d.isInternetExplorer.cached=typeof d.isInternetExplorer.cached!=="undefined"?d.isInternetExplorer.cached:d.getInternetExplorerMajorVersion()!==0};b.emulated={pushState:!Boolean(h.history&&h.history.pushState&&
h.history.replaceState)};d.isEmptyObject=function(a){for(var c in a)if(this.hasOwnProperty(c))return false;return true};d.cloneObject=function(a){if(a){a=JSON.stringify(a);a=JSON.parse(a)}else a={};return a};b.contractUrl=function(a){a=b.expandUrl(a);var c=g.location.protocol+"//"+(g.location.hostname||g.location.host);if(g.location.port)c+=":"+g.location.port;c+="/";return a=a.replace(c,"/")};b.expandUrl=function(a){a=a||"";if(!/[a-z]+\:\/\//.test(a))if(a.length===0||a.substring(0,1)==="?")a=g.location.href.replace(/[#\?].*/,
"")+a;else{var c=g.getElementsByTagName("base"),e=null;e="";if(c.length===1){e=c[0];e=e.href;if(e[e.length-1]!=="/")e+="/";a=e+a.replace(/^\//,"")}else if(a.substring(0,1)==="."){c=g.location.href.replace(/[#\?].*/,"").replace(/[^\/]+$/,"");if(c[c.length-1]!=="/")c+="/";a=c+a}else{c=g.location.protocol+"//"+(g.location.hostname||g.location.host);if(g.location.port)c+=":"+g.location.port;c+="/";a=c+a.replace(/^\//,"")}}return a};b.expandState=function(a){a=a||{};a={data:a.data||{},url:b.expandUrl(a.url||
""),title:a.title||""};a.data.title=a.data.title||a.title;a.data.url=a.data.url||a.url;return a};b.createStateObject=function(a,c,e){a={data:a,title:c,url:e};return a=b.expandState(a)};b.expandHash=function(a){var c=null;try{c=JSON.parse(a)}catch(e){var f=/(.*)\/uid=([0-9]+)$/.exec(a);if(f=f?String(f[2]||""):"")c=d.getStateByUid(f)||null;if(!c&&/\//.test(a)){a=b.expandUrl(a);c=b.createStateObject(null,null,a)}}return c=c?b.expandState(c):null};b.contractState=function(a){if(!a)return null;var c=null;
if(a=d.cloneObject(a)){a.data=a.data||{};delete a.data.title;delete a.data.url;if(d.isEmptyObject(a)&&!a.title)c=b.contractUrl(a.url);else{c=JSON.stringify(a);var e;if(typeof d.hashesToUids[c]!=="undefined")e=d.hashesToUids[c];else for(;;){e=String(Math.floor(Math.random()*1E3));if(typeof d.uidsToStates[e]==="undefined")break}d.hashesToUids[c]=e;d.uidsToStates[e]=a;c=b.contractUrl(a.url)+"/uid="+e}}return c};d.uidsToStates={};d.hashesToUids={};d.getStateByUid=function(a){return d.uidsToStates[String(a)]||
k};d.statesByUrl={};d.duplicateStateUrls={};d.statesByHash={};d.savedStates=[];b.getState=function(){return d.getStateByIndex()};b.getStateHash=function(){return b.contractState(b.getState())};d.getStateByUrl=function(a){return d.statesByUrl[a]||k};d.getStateByHash=function(a){return d.statesByHash[a]||k};d.storeState=function(a){var c=b.contractState(a),e=d.getStateByUrl(a.url);if(typeof e!=="undefined")if(b.contractState(e)!==c)d.duplicateStateUrls[a.url]=true;d.statesByUrl[a.url]=d.statesByHash[c]=
a;return true};d.isLastState=function(a){a=b.contractState(a);var c=b.getStateHash();return d.savedStates.length&&a===c};d.saveState=function(a){if(d.isLastState(a))return false;d.savedStates.push(a);return true};d.getStateByIndex=function(a){var c=null;return c=typeof a==="undefined"?d.savedStates[d.savedStates.length-1]:a<0?d.savedStates[d.savedStates.length+a]:d.savedStates[a]};d.stateUrlExists=function(a){return typeof d.statesByUrl[a]!=="undefined"};d.urlDuplicateExists=function(a){return typeof d.duplicateStateUrls[a]!==
"undefined"};b.getHash=function(){return d.unescapeHash(g.location.hash)};d.unescapeHash=function(a){a=d.normalizeHash(a);if(/[\%]/.test(a))a=unescape(a);return a};d.normalizeHash=function(a){return a.replace(/[^#]*#/,"").replace(/#.*/,"")};b.setHash=function(a,c){if(c!==false&&b.busy()){b.debug("History.setHash: we must wait",arguments);b.pushQueue({scope:b,callback:b.setHash,args:arguments,queue:c});return false}var e=d.escapeHash(a);b.debug("History.setHash",this,arguments,"hash:",a,"adjustedHash:",
e,"oldHash:",g.location.hash);b.busy(true);g.location.hash=e;return a};d.escapeHash=function(a){a=d.normalizeHash(a);if(/[^a-zA-Z0-9\/\-\_\%\.]/.test(a))a=escape(a);return a};b.extractHashFromUrl=function(a){a=String(a).replace(/([^#]*)#?([^#]*)#?(.*)/,"$2");return a=d.unescapeHash(a)};b.isTraditionalAnchor=function(a){a=b.extractHashFromUrl(a);return typeof g.getElementById(a)!=="undefined"};b.queues=[];b.busy=function(a){b.debug("History.busy: called: changing ["+(b.busy.flag||false)+"] to ["+(a||
false)+"]",b.queues);if(typeof a!=="undefined")b.busy.flag=a;else if(typeof b.busy.flag==="undefined")b.busy.flag=false;if(!b.busy.flag){clearTimeout(b.busy.timeout);var c=function(){if(!b.busy.flag)for(var e=b.queues.length-1;e>=0;--e){var f=b.queues[e];if(f.length!==0){f=f.shift();b.debug("History.busy: firing",f);b.fireQueueItem(f);b.busy.timeout=setTimeout(c,b.options.busyDelay)}}};b.busy.timeout=setTimeout(c,b.options.busyDelay)}return b.busy.flag};b.fireQueueItem=function(a){return a.callback.apply(a.scope||
b,a.args||[])};b.pushQueue=function(a){b.debug("History.pushQueue: called",arguments);b.queues[a.queue||0]=b.queues[a.queue||0]||[];b.queues[a.queue||0].push(a);return true};b.queue=function(a,c){if(typeof a==="function")a={callback:a};if(typeof c!=="undefined")a.queue=c;b.busy()?b.pushQueue(a):b.fireQueueItem(a);return true};b.back=function(a){b.debug("History.back: called",arguments);if(a!==false&&b.busy()){b.debug("History.back: we must wait",arguments);b.pushQueue({scope:b,callback:b.back,args:arguments,
queue:a});return false}b.busy(true);if(b.emulated.hashChange&&d.isInternetExplorer()){var c=b.getHash();setTimeout(function(){if(b.getHash()===c){b.debug("History.back: trying again");return b.back(false)}return true},b.options.hashChangeCheckerDelay*5)}l.go(-1);return true};b.forward=function(a){b.debug("History.forward: called",arguments);if(a!==false&&b.busy()){b.debug("History.forward: we must wait",arguments);b.pushQueue({scope:b,callback:b.forward,args:arguments,queue:a});return false}b.busy(true);
if(b.emulated.hashChange&&d.isInternetExplorer()){var c=b.getHash();setTimeout(function(){if(b.getHash()===c){b.debug("History.forward: trying again");return b.forward(false)}return true},b.options.hashChangeCheckerDelay*5)}l.go(1);return true};b.go=function(a,c){b.debug("History.go: called",arguments);if(a>0)for(var e=1;e<=a;++e)b.forward(c);else if(a<0)for(e=-1;e>=a;--e)b.back(c);else throw Error("History.go: History.go requires a positive or negative integer passed.");return true};if(!b.emulated.pushState){d.onPopState=
function(a){b.debug("_History.onPopState",this,arguments);var c=unescape(b.getHash());if(c){var e=b.expandHash(c);if(e){b.debug("_History.onPopState: state anchor",c,e);b.replaceState(e.data,e.tite,e.url,false)}else{b.debug("_History.onPopState: traditional anchor",c);b.Adapter.trigger(h,"anchorchange");b.busy(false)}return false}c={};var f=e=null;c=null;a=a||{};if(typeof a.state==="undefined")if(typeof a.originalEvent!=="undefined"&&typeof a.originalEvent.state!=="undefined")a.state=a.originalEvent.state;
else if(typeof a.event!=="undefined"&&typeof a.event.state!=="undefined")a.state=a.event.state;if(a.state===null)c=a.state;else if(typeof a.state!=="undefined"){e=b.expandUrl(g.location.href);c=d.getStateByUrl(e);e=d.urlDuplicateExists(e);c=typeof c!=="undefined"&&!e?c.data:a.state}else{e=b.expandUrl(g.location.href);if((c=d.getStateByUrl(e))&&e==c.url)c=c.data;else throw Error("Unknown state");}c=typeof c!=="object"||c===null?{}:c;e=c.title||"";f=c.url||g.location.href;c=b.createStateObject(c,e,
f);if(d.isLastState(c)){b.debug("_History.onPopState: no change",c,d.savedStates);b.busy(false);return false}b.debug("_History.onPopState","newState:",c,"oldState:",d.getStateByUrl(b.expandUrl(g.location.href)),"duplicateExists:",d.urlDuplicateExists(b.expandUrl(g.location.href)));d.storeState(c);d.saveState(c);if(c.title)g.title=c.title;b.Adapter.trigger(h,"statechange");b.busy(false);return true};b.Adapter.bind(h,"popstate",d.onPopState);b.pushState=function(a,c,e,f){if(b.extractHashFromUrl(e))throw Error("History.js does not support states with fragement-identifiers (hashes/anchors).");
if(f!==false&&b.busy()){b.debug("History.pushState: we must wait",arguments);b.pushQueue({scope:b,callback:b.pushState,args:arguments,queue:f});return false}b.busy(true);var i=b.createStateObject(a,c,e);d.storeState(i);l.pushState(i.data,i.title,i.url);b.Adapter.trigger(h,"popstate");return true};b.replaceState=function(a,c,e,f){if(b.extractHashFromUrl(e))throw Error("History.js does not support states with fragement-identifiers (hashes/anchors).");if(f!==false&&b.busy()){b.debug("History.replaceState: we must wait",
arguments);b.pushQueue({scope:b,callback:b.replaceState,args:arguments,queue:f});return false}b.busy(true);var i=b.createStateObject(a,c,e);d.storeState(i);l.replaceState(i.data,i.title,i.url);b.Adapter.trigger(h,"popstate");return true};if(navigator.vendor==="Apple Computer, Inc."){b.Adapter.onDomLoad(function(){b.debug("Safari Initial State Change Fix");var a=b.createStateObject({},"",g.location.href);b.pushState(a.data,a.title,a.url)});b.Adapter.bind(h,"hashchange",function(){b.Adapter.trigger(h,
"popstate")})}}};b.initHtml5()})(window);
